### ISSUE TITLE
1.20.1 version crashes when used on server

### ISSUE THREAD

**Issue by HaXrDEV** [izofar/bygone-nether#35]
### Describe the Bug

Crashes the server when Bygone Nether is installed.
Not an issue in singleplayer.

### Reproduction Steps

1. Put mod in mod folder.
2. Watch the server crash.

### Expected Result

Not crashing.

### Crash Report or Log

https://gist.github.com/HaXrBOT/a13d9d8d097a1dacc61cb7e80147bdbf

### Operating System

Windows 11

### Mod Version

1.3.2

### Minecraft Version

1.20.1

### Mod Loader

Fabric

### Mod Loader Version

0.14.22

### Other Mods

https://gist.github.com/HaXrBOT/c4afb0cae796440b72d4bc2e2648768c

**Comment by HaXrDEV** [comment]
Just tested with only Bygone Nether and Fabric API installed. It still crashes: https://gist.github.com/HaXrBOT/d55f91bd508f85698b0fef37533843f1

**Comment by Sunconure11** [comment]
Happens on 1.19.2 too

https://gist.github.com/Sunconure11/e269632d2c51554feced6fc0bdb73af7

**Comment by izofar** [comment]
Fixed for 1.20.1 in [9846601](https://github.com/izofar/bygone-nether/commit/98466017fed8bb5e9e7cfba00d3673e15dcd0661), and 1.19.2 in [14261a3](https://github.com/izofar/bygone-nether/commit/14261a3539ab1e13b9bf60b0fc29f113bffdd69e)

**Comment by HaXrDEV** [comment]
Letting you know that it still happens in the latest 1.18.2 version (bygonenether-1.18-1.3.2.jar)
https://gist.github.com/HaXrBOT/112e46615b6bcff029a4720771f8c0e2
